### ISSUE TITLE
crash when starting

### ISSUE THREAD

**Issue by Wolkenfarmer** [abc013/WarriorsSnuggery#20]
Game crashes, when trying to start. The playtest is specified for a special audio software, which I would like to be undone ^.^.'. I tried it with every selectable audio-ouput on my device, getting the same error. Version 1.4 still works for me, so one of the new mechanics seems to make the difference here.

__exception log:__
> openal32.dll
> System.DllNotFoundException: openal32.dll
>    bei OpenTK.Audio.AudioContext.CreateContext(String device, Int32 freq, Int32 refresh, Boolean sync, Boolean enableEfx, MaxAuxiliarySends efxAuxiliarySends)
>    bei OpenTK.Audio.AudioContext..ctor(String device)
>    bei WarriorsSnuggery.Audio.AudioDevice..ctor()
>    bei WarriorsSnuggery.AudioController.Load()
>    bei WarriorsSnuggery.Window.OnLoad(EventArgs e)
>    bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
>    bei WarriorsSnuggery.Program.run()
>    bei WarriorsSnuggery.Program.Main()

__debug log:__
> SHADER 1 locations: 0, 1, 2, 3;
> SHADER 2 locations: 0, 1, 3, 4;
> SHADER 3 locations: 0, 1, 3, 4;
> SHADER 4 locations: 0, 1, 3, 4;
> SHADER 4 shadowloc: 5

__performance log:__
> 61ms		<- Configuring GL
> 133ms		<- Loading Fonts

Even after installing the required software the game crashes - this time without exception nor entry in its log.

__debug log:__
> SHADER 1 locations: 0, 1, 2, 3;
> SHADER 2 locations: 0, 1, 3, 4;
> SHADER 3 locations: 0, 1, 3, 4;
> SHADER 4 locations: 0, 1, 3, 4;
> SHADER 4 shadowloc: 5

__performance log:__
> 55ms		<- Configuring GL
> 122ms		<- Loading Fonts
> 585ms		<- Loading Sound

**Comment by abc013** [comment]
Ahh right. Forgot to attach the `openal32.dll`. Thanks for the report :)
